// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class AssociationType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassAssociationType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceAssociationType
	{		
		public AssociationType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static AssociationType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (AssociationType) session.Instantiate(id);		
		}
	}
}