// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class MetaAssociation : global::Allors.Meta.AllorsGenerated.AllorsClassAssociationType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceAssociationType
	{		
		public MetaAssociation(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaAssociation Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaAssociation) session.Instantiate(id);		
		}
	}
}