// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class Domain : global::Allors.R1.Meta.AllorsGenerated.AllorsClassDomain, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceDomain
	{		
		public Domain(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static Domain Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (Domain) session.Instantiate(id);		
		}
	}
}