// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class Domain : global::Allors.Meta.AllorsGenerated.AllorsClassDomain, global::Allors.Meta.AllorsGenerated.AllorsInterfaceDomain
	{		
		public Domain(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static Domain Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (Domain) session.Instantiate(id);		
		}
	}
}