// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class Inheritance : global::Allors.Meta.AllorsGenerated.AllorsClassInheritance, global::Allors.Meta.AllorsGenerated.AllorsInterfaceInheritance
	{		
		public Inheritance(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static Inheritance Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (Inheritance) session.Instantiate(id);		
		}
	}
}