// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class Inheritance : global::Allors.R1.Meta.AllorsGenerated.AllorsClassInheritance, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceInheritance
	{		
		public Inheritance(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static Inheritance Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (Inheritance) session.Instantiate(id);		
		}
	}
}