// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public abstract partial class MetaObject : global::Allors.Meta.AllorsGenerated.AllorsClassMetaObject, global::Allors.Meta.AllorsGenerated.AllorsInterfaceMetaObject
	{		
		public MetaObject(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public static MetaObject Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaObject) session.Instantiate(id);		
		}
	}
}