// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public abstract partial class MetaObject : global::Allors.R1.Meta.AllorsGenerated.AllorsClassMetaObject, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceMetaObject
	{		
		public MetaObject(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public static MetaObject Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaObject) session.Instantiate(id);		
		}
	}
}