// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class MethodType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassMethodType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceMethodType
	{		
		public MethodType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MethodType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MethodType) session.Instantiate(id);		
		}
	}
}