// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class MetaMethod : global::Allors.Meta.AllorsGenerated.AllorsClassMethodType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceMethodType
	{		
		public MetaMethod(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaMethod Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaMethod) session.Instantiate(id);		
		}
	}
}