// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class MetaObject : global::Allors.Meta.AllorsGenerated.AllorsClassObjectType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceObjectType
	{		
		public MetaObject(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaObject Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaObject) session.Instantiate(id);		
		}
	}
}