// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class ObjectType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassObjectType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceObjectType
	{		
		public ObjectType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static ObjectType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (ObjectType) session.Instantiate(id);		
		}
	}
}