// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public abstract partial class MetaOperand : global::Allors.Meta.AllorsGenerated.AllorsClassOperandType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceOperandType
	{		
		public MetaOperand(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaOperand Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaOperand) session.Instantiate(id);		
		}
	}
}