// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public abstract partial class OperandType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassOperandType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceOperandType
	{		
		public OperandType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static OperandType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (OperandType) session.Instantiate(id);		
		}
	}
}