// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public abstract partial class PropertyType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassPropertyType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfacePropertyType
	{		
		public PropertyType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static PropertyType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (PropertyType) session.Instantiate(id);		
		}
	}
}