// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public abstract partial class MetaProperty : global::Allors.Meta.AllorsGenerated.AllorsClassPropertyType, global::Allors.Meta.AllorsGenerated.AllorsInterfacePropertyType
	{		
		public MetaProperty(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaProperty Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaProperty) session.Instantiate(id);		
		}
	}
}