// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class RelationType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassRelationType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceRelationType
	{		
		public RelationType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static RelationType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (RelationType) session.Instantiate(id);		
		}
	}
}