// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class RelationType : global::Allors.Meta.AllorsGenerated.AllorsClassRelationType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceRelationType
	{		
		public RelationType(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static RelationType Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (RelationType) session.Instantiate(id);		
		}
	}
}