// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.R1.Meta
{
	public  partial class RoleType : global::Allors.R1.Meta.AllorsGenerated.AllorsClassRoleType, global::Allors.R1.Meta.AllorsGenerated.AllorsInterfaceRoleType
	{		
		public RoleType(Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static RoleType Instantiate (global::Allors.R1.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (RoleType) session.Instantiate(id);		
		}
	}
}