// Allors generated file. 
// Do not edit this file, changes will be overwritten.

namespace Allors.Meta
{
    using Allors.Meta.AllorsGenerated;

    public  partial class MetaRole : global::Allors.Meta.AllorsGenerated.AllorsClassRoleType, global::Allors.Meta.AllorsGenerated.AllorsInterfaceRoleType
	{		
		public MetaRole(AllorsEmbeddedSession session, System.Int32 id) : base(session, id) {}

		public new static MetaRole Instantiate (global::Allors.Meta.AllorsGenerated.AllorsEmbeddedSession session, System.Int32 id)
		{
			return (MetaRole) session.Instantiate(id);		
		}
	}
}