// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface I34 : Allors.IObject
	{


		global::System.String I34AllorsString 
		{
			get;
			set;
		}

		bool ExistI34AllorsString{get;}

		void RemoveI34AllorsString();


		global::System.Int32? I34AllorsInteger 
		{
			get;
			set;
		}

		bool ExistI34AllorsInteger{get;}

		void RemoveI34AllorsInteger();


		global::System.Double? I34AllorsDouble 
		{
			get;
			set;
		}

		bool ExistI34AllorsDouble{get;}

		void RemoveI34AllorsDouble();


		global::System.Boolean? I34AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistI34AllorsBoolean{get;}

		void RemoveI34AllorsBoolean();


		global::System.Decimal? I34AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistI34AllorsDecimal{get;}

		void RemoveI34AllorsDecimal();



		global::Domain.I12 I12WhereI34one2one
		{
			get;
		}

		bool ExistI12WhereI34one2one
		{
			get;
		}


		global::Domain.I1 I1WhereI34one2one
		{
			get;
		}

		bool ExistI1WhereI34one2one
		{
			get;
		}


		Allors.Extent<global::Domain.I1> I1sWhereI34many2many
		{ 
			get;
		}

		bool ExistI1sWhereI34many2many
		{
			get;
		}


		Allors.Extent<global::Domain.I12> I12sWhereI34many2many
		{ 
			get;
		}

		bool ExistI12sWhereI34many2many
		{
			get;
		}


		Allors.Extent<global::Domain.I12> I12sWhereI34many2one
		{ 
			get;
		}

		bool ExistI12sWhereI34many2one
		{
			get;
		}


		Allors.Extent<global::Domain.I1> I1sWhereI34many2one
		{ 
			get;
		}

		bool ExistI1sWhereI34many2one
		{
			get;
		}


		global::Domain.I12 I12WhereI34one2many
		{
			get;
		}

		bool ExistI12WhereI34one2many
		{
			get;
		}


		global::Domain.I1 I1WhereI34one2many
		{
			get;
		}

		bool ExistI1WhereI34one2many
		{
			get;
		}

	}

}