// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface I4 :  global::Domain.S4,global::Domain.S1234, Allors.IObject
	{


		global::Domain.C3 C3WhereI4one2one
		{
			get;
		}

		bool ExistC3WhereI4one2one
		{
			get;
		}


		global::Domain.I3 I3WhereI4one2many
		{
			get;
		}

		bool ExistI3WhereI4one2many
		{
			get;
		}


		Allors.Extent<global::Domain.I3> I3sWhereI4many2many
		{ 
			get;
		}

		bool ExistI3sWhereI4many2many
		{
			get;
		}


		Allors.Extent<global::Domain.I3> I3sWhereI4many2one
		{ 
			get;
		}

		bool ExistI3sWhereI4many2one
		{
			get;
		}


		Allors.Extent<global::Domain.C3> C3sWhereI4many2many
		{ 
			get;
		}

		bool ExistC3sWhereI4many2many
		{
			get;
		}


		Allors.Extent<global::Domain.C3> C3sWhereI4many2one
		{ 
			get;
		}

		bool ExistC3sWhereI4many2one
		{
			get;
		}


		global::Domain.I3 I3WhereI4one2one
		{
			get;
		}

		bool ExistI3WhereI4one2one
		{
			get;
		}


		global::Domain.C3 C3WhereI4one2many
		{
			get;
		}

		bool ExistC3WhereI4one2many
		{
			get;
		}

	}

}