// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface IGT32Composite : Allors.IObject
	{


		global::Domain.IGT32Composite Self16
		{ 
			get;
			set;
		}

		bool ExistSelf16
		{
			get;
		}

		void RemoveSelf16();


		global::Domain.IGT32Composite Self10
		{ 
			get;
			set;
		}

		bool ExistSelf10
		{
			get;
		}

		void RemoveSelf10();


		global::Domain.IGT32Composite Self19
		{ 
			get;
			set;
		}

		bool ExistSelf19
		{
			get;
		}

		void RemoveSelf19();


		global::Domain.IGT32Composite Self5
		{ 
			get;
			set;
		}

		bool ExistSelf5
		{
			get;
		}

		void RemoveSelf5();


		global::Domain.IGT32Composite Self15
		{ 
			get;
			set;
		}

		bool ExistSelf15
		{
			get;
		}

		void RemoveSelf15();


		global::Domain.IGT32Composite Self1
		{ 
			get;
			set;
		}

		bool ExistSelf1
		{
			get;
		}

		void RemoveSelf1();


		global::Domain.IGT32Composite Self30
		{ 
			get;
			set;
		}

		bool ExistSelf30
		{
			get;
		}

		void RemoveSelf30();


		global::Domain.IGT32Composite Self27
		{ 
			get;
			set;
		}

		bool ExistSelf27
		{
			get;
		}

		void RemoveSelf27();


		global::Domain.IGT32Composite Self33
		{ 
			get;
			set;
		}

		bool ExistSelf33
		{
			get;
		}

		void RemoveSelf33();


		global::Domain.IGT32Composite Self28
		{ 
			get;
			set;
		}

		bool ExistSelf28
		{
			get;
		}

		void RemoveSelf28();


		global::Domain.IGT32Composite Self32
		{ 
			get;
			set;
		}

		bool ExistSelf32
		{
			get;
		}

		void RemoveSelf32();


		global::Domain.IGT32Composite Self11
		{ 
			get;
			set;
		}

		bool ExistSelf11
		{
			get;
		}

		void RemoveSelf11();


		global::Domain.IGT32Composite Self9
		{ 
			get;
			set;
		}

		bool ExistSelf9
		{
			get;
		}

		void RemoveSelf9();


		global::Domain.IGT32Composite Self20
		{ 
			get;
			set;
		}

		bool ExistSelf20
		{
			get;
		}

		void RemoveSelf20();


		global::Domain.IGT32Composite Self25
		{ 
			get;
			set;
		}

		bool ExistSelf25
		{
			get;
		}

		void RemoveSelf25();


		global::Domain.IGT32Composite Self6
		{ 
			get;
			set;
		}

		bool ExistSelf6
		{
			get;
		}

		void RemoveSelf6();


		global::Domain.IGT32Composite Self7
		{ 
			get;
			set;
		}

		bool ExistSelf7
		{
			get;
		}

		void RemoveSelf7();


		global::Domain.IGT32Composite Self12
		{ 
			get;
			set;
		}

		bool ExistSelf12
		{
			get;
		}

		void RemoveSelf12();


		global::Domain.IGT32Composite Self24
		{ 
			get;
			set;
		}

		bool ExistSelf24
		{
			get;
		}

		void RemoveSelf24();


		global::Domain.IGT32Composite Self8
		{ 
			get;
			set;
		}

		bool ExistSelf8
		{
			get;
		}

		void RemoveSelf8();


		global::Domain.IGT32Composite Self4
		{ 
			get;
			set;
		}

		bool ExistSelf4
		{
			get;
		}

		void RemoveSelf4();


		global::Domain.IGT32Composite Self26
		{ 
			get;
			set;
		}

		bool ExistSelf26
		{
			get;
		}

		void RemoveSelf26();


		global::Domain.IGT32Composite Self29
		{ 
			get;
			set;
		}

		bool ExistSelf29
		{
			get;
		}

		void RemoveSelf29();


		global::Domain.IGT32Composite Self3
		{ 
			get;
			set;
		}

		bool ExistSelf3
		{
			get;
		}

		void RemoveSelf3();


		global::Domain.IGT32Composite Self17
		{ 
			get;
			set;
		}

		bool ExistSelf17
		{
			get;
		}

		void RemoveSelf17();


		global::Domain.IGT32Composite Self18
		{ 
			get;
			set;
		}

		bool ExistSelf18
		{
			get;
		}

		void RemoveSelf18();


		global::Domain.IGT32Composite Self22
		{ 
			get;
			set;
		}

		bool ExistSelf22
		{
			get;
		}

		void RemoveSelf22();


		global::Domain.IGT32Composite Self23
		{ 
			get;
			set;
		}

		bool ExistSelf23
		{
			get;
		}

		void RemoveSelf23();


		global::Domain.IGT32Composite Self2
		{ 
			get;
			set;
		}

		bool ExistSelf2
		{
			get;
		}

		void RemoveSelf2();


		global::Domain.IGT32Composite Self21
		{ 
			get;
			set;
		}

		bool ExistSelf21
		{
			get;
		}

		void RemoveSelf21();


		global::Domain.IGT32Composite Self14
		{ 
			get;
			set;
		}

		bool ExistSelf14
		{
			get;
		}

		void RemoveSelf14();


		global::Domain.IGT32Composite Self31
		{ 
			get;
			set;
		}

		bool ExistSelf31
		{
			get;
		}

		void RemoveSelf31();


		global::Domain.IGT32Composite Self13
		{ 
			get;
			set;
		}

		bool ExistSelf13
		{
			get;
		}

		void RemoveSelf13();



		global::Domain.IGT32Composite IGT32CompositeWhereSelf16
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf16
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf10
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf10
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf19
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf19
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf5
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf5
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf15
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf15
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf1
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf1
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf30
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf30
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf27
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf27
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf33
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf33
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf28
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf28
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf32
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf32
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf11
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf11
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf9
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf9
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf20
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf20
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf25
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf25
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf6
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf6
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf7
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf7
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf12
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf12
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf24
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf24
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf8
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf8
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf4
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf4
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf26
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf26
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf29
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf29
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf3
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf3
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf17
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf17
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf18
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf18
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf22
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf22
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf23
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf23
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf2
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf2
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf21
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf21
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf14
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf14
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf31
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf31
		{
			get;
		}


		global::Domain.IGT32Composite IGT32CompositeWhereSelf13
		{
			get;
		}

		bool ExistIGT32CompositeWhereSelf13
		{
			get;
		}

	}

}