// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface InterfaceWithoutConcreteClass : Allors.IObject
	{


		global::System.Boolean? AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistAllorsBoolean{get;}

		void RemoveAllorsBoolean();

	}

}