// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public  partial class LT32UnitGT32Composite : LT32UnitGT32CompositeAllors 
	{
		public LT32UnitGT32Composite(Allors.IStrategy allors) : base(allors) {}

		public static LT32UnitGT32Composite Instantiate (Allors.ISession allorsSession, string allorsObjectId)
		{
			return (LT32UnitGT32Composite) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class LT32UnitGT32CompositeAllors :  Allors.ObjectBase 
	{
		protected LT32UnitGT32CompositeAllors(Allors.IStrategy allors) : base(allors){}
	}
}