// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface Named : Allors.IObject
	{


		global::System.Int32? Index 
		{
			get;
			set;
		}

		bool ExistIndex{get;}

		void RemoveIndex();


		global::System.String Name 
		{
			get;
			set;
		}

		bool ExistName{get;}

		void RemoveName();



		global::Domain.Company CompanyWhereNamedOneSort1
		{
			get;
		}

		bool ExistCompanyWhereNamedOneSort1
		{
			get;
		}


		Allors.Extent<global::Domain.Company> CompaniesWhereNamedManySort2
		{ 
			get;
		}

		bool ExistCompaniesWhereNamedManySort2
		{
			get;
		}


		Allors.Extent<global::Domain.Company> CompaniesWhereNamedManySort1
		{ 
			get;
		}

		bool ExistCompaniesWhereNamedManySort1
		{
			get;
		}


		global::Domain.Company CompanyWhereNamedOneSort2
		{
			get;
		}

		bool ExistCompanyWhereNamedOneSort2
		{
			get;
		}

	}

}