// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface S1234 : Allors.IObject
	{


		global::System.Double? S1234AllorsDouble 
		{
			get;
			set;
		}

		bool ExistS1234AllorsDouble{get;}

		void RemoveS1234AllorsDouble();


		global::System.Decimal? S1234AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistS1234AllorsDecimal{get;}

		void RemoveS1234AllorsDecimal();


		global::System.Int32? S1234AllorsInteger 
		{
			get;
			set;
		}

		bool ExistS1234AllorsInteger{get;}

		void RemoveS1234AllorsInteger();


		global::Domain.S1234 S1234many2one
		{ 
			get;
			set;
		}

		bool ExistS1234many2one
		{
			get;
		}

		void RemoveS1234many2one();


		global::Domain.C2 S1234C2one2one
		{ 
			get;
			set;
		}

		bool ExistS1234C2one2one
		{
			get;
		}

		void RemoveS1234C2one2one();


		Allors.Extent<global::Domain.C2> S1234C2many2manies
		{ 
			get;
			set;
		}

		void AddS1234C2many2many (global::Domain.C2 value);

		void RemoveS1234C2many2many (global::Domain.C2 value);

		bool ExistS1234C2many2manies
		{
			get;
		}

		void RemoveS1234C2many2manies();


		Allors.Extent<global::Domain.S1234> S1234one2manies
		{ 
			get;
			set;
		}

		void AddS1234one2many (global::Domain.S1234 value);

		void RemoveS1234one2many (global::Domain.S1234 value);

		bool ExistS1234one2manies
		{
			get;
		}

		void RemoveS1234one2manies();


		Allors.Extent<global::Domain.C2> S1234C2one2manies
		{ 
			get;
			set;
		}

		void AddS1234C2one2many (global::Domain.C2 value);

		void RemoveS1234C2one2many (global::Domain.C2 value);

		bool ExistS1234C2one2manies
		{
			get;
		}

		void RemoveS1234C2one2manies();


		Allors.Extent<global::Domain.S1234> S1234many2manies
		{ 
			get;
			set;
		}

		void AddS1234many2many (global::Domain.S1234 value);

		void RemoveS1234many2many (global::Domain.S1234 value);

		bool ExistS1234many2manies
		{
			get;
		}

		void RemoveS1234many2manies();


		global::System.Int64? S1234AllorsLong 
		{
			get;
			set;
		}

		bool ExistS1234AllorsLong{get;}

		void RemoveS1234AllorsLong();


		global::System.String ClassName 
		{
			get;
			set;
		}

		bool ExistClassName{get;}

		void RemoveClassName();


		global::System.DateTime? S1234AllorsDateTime 
		{
			get;
			set;
		}

		bool ExistS1234AllorsDateTime{get;}

		void RemoveS1234AllorsDateTime();


		global::Domain.S1234 S1234one2one
		{ 
			get;
			set;
		}

		bool ExistS1234one2one
		{
			get;
		}

		void RemoveS1234one2one();


		global::Domain.C2 S1234C2many2one
		{ 
			get;
			set;
		}

		bool ExistS1234C2many2one
		{
			get;
		}

		void RemoveS1234C2many2one();


		global::System.String S1234AllorsString 
		{
			get;
			set;
		}

		bool ExistS1234AllorsString{get;}

		void RemoveS1234AllorsString();


		global::System.Boolean? S1234AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistS1234AllorsBoolean{get;}

		void RemoveS1234AllorsBoolean();



		Allors.Extent<global::Domain.S1234> S1234sWhereS1234many2one
		{ 
			get;
		}

		bool ExistS1234sWhereS1234many2one
		{
			get;
		}


		global::Domain.S1234 S1234WhereS1234one2many
		{
			get;
		}

		bool ExistS1234WhereS1234one2many
		{
			get;
		}


		Allors.Extent<global::Domain.S1234> S1234sWhereS1234many2many
		{ 
			get;
		}

		bool ExistS1234sWhereS1234many2many
		{
			get;
		}


		global::Domain.S1234 S1234WhereS1234one2one
		{
			get;
		}

		bool ExistS1234WhereS1234one2one
		{
			get;
		}

	}

}