// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public abstract partial class A4 : A4Allors , global::Domain.AI4, global::Domain.AI34
	{
		public A4(Allors.R1.IStrategy allors) : base(allors) {}

		public static new A4 Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (A4) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class A4Allors :  global::Domain.A34 
	{
		protected A4Allors(Allors.R1.IStrategy allors) : base(allors){}



		virtual public global::System.String A4AllorsString 
		{
			get
			{
				return (global::System.String) Strategy.GetUnitRole(A4Meta.A4AllorsString);
			}
			set
			{
				Strategy.SetUnitRole(A4Meta.A4AllorsString, value);
			}
		}

		virtual public bool ExistA4AllorsString{
			get
			{
				return Strategy.ExistUnitRole(A4Meta.A4AllorsString);
			}
		}

		virtual public void RemoveA4AllorsString()
		{
			Strategy.RemoveUnitRole(A4Meta.A4AllorsString);
		}

	}
}