// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public  partial class ClassWithoutUnitRoles : ClassWithoutUnitRolesAllors 
	{
		public ClassWithoutUnitRoles(Allors.R1.IStrategy allors) : base(allors) {}

		public static ClassWithoutUnitRoles Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (ClassWithoutUnitRoles) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class ClassWithoutUnitRolesAllors :  Allors.R1.ObjectBase 
	{
		protected ClassWithoutUnitRolesAllors(Allors.R1.IStrategy allors) : base(allors){}
	}
}