// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public  partial class LT32 : LT32Allors 
	{
		public LT32(Allors.R1.IStrategy allors) : base(allors) {}

		public static LT32 Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (LT32) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class LT32Allors :  Allors.R1.ObjectBase 
	{
		protected LT32Allors(Allors.R1.IStrategy allors) : base(allors){}
	}
}