// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface S12 : Allors.R1.IObject
	{


		global::System.String S12AllorsString 
		{
			get;
			set;
		}

		bool ExistS12AllorsString{get;}

		void RemoveS12AllorsString();


		global::System.DateTime? S12AllorsDateTime 
		{
			get;
			set;
		}

		bool ExistS12AllorsDateTime{get;}

		void RemoveS12AllorsDateTime();


		Allors.R1.Extent<global::Domain.C2> S12C2many2manies
		{ 
			get;
			set;
		}

		void AddS12C2many2many (global::Domain.C2 value);

		void RemoveS12C2many2many (global::Domain.C2 value);

		bool ExistS12C2many2manies
		{
			get;
		}

		void RemoveS12C2many2manies();


		global::Domain.C2 S12C2many2one
		{ 
			get;
			set;
		}

		bool ExistS12C2many2one
		{
			get;
		}

		void RemoveS12C2many2one();


		global::Domain.C2 S12C2one2one
		{ 
			get;
			set;
		}

		bool ExistS12C2one2one
		{
			get;
		}

		void RemoveS12C2one2one();


		Allors.R1.Extent<global::Domain.C2> S12C2one2manies
		{ 
			get;
			set;
		}

		void AddS12C2one2many (global::Domain.C2 value);

		void RemoveS12C2one2many (global::Domain.C2 value);

		bool ExistS12C2one2manies
		{
			get;
		}

		void RemoveS12C2one2manies();


		global::System.Boolean? S12AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistS12AllorsBoolean{get;}

		void RemoveS12AllorsBoolean();


		global::System.Double? S12AllorsDouble 
		{
			get;
			set;
		}

		bool ExistS12AllorsDouble{get;}

		void RemoveS12AllorsDouble();


		global::System.Int32? S12AllorsInteger 
		{
			get;
			set;
		}

		bool ExistS12AllorsInteger{get;}

		void RemoveS12AllorsInteger();


		global::System.Decimal? S12AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistS12AllorsDecimal{get;}

		void RemoveS12AllorsDecimal();

	}

}