// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface I23 : Allors.R1.IObject
	{


		global::System.String I23AllorsString 
		{
			get;
			set;
		}

		bool ExistI23AllorsString{get;}

		void RemoveI23AllorsString();

	}

}