// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface I3 :  global::Domain.S1234,global::Domain.S3, Allors.R1.IObject
	{


		Allors.R1.Extent<global::Domain.C4> I3C4many2manies
		{ 
			get;
			set;
		}

		void AddI3C4many2many (global::Domain.C4 value);

		void RemoveI3C4many2many (global::Domain.C4 value);

		bool ExistI3C4many2manies
		{
			get;
		}

		void RemoveI3C4many2manies();


		global::System.String I3AllorsString 
		{
			get;
			set;
		}

		bool ExistI3AllorsString{get;}

		void RemoveI3AllorsString();


		Allors.R1.Extent<global::Domain.I4> I3I4one2manies
		{ 
			get;
			set;
		}

		void AddI3I4one2many (global::Domain.I4 value);

		void RemoveI3I4one2many (global::Domain.I4 value);

		bool ExistI3I4one2manies
		{
			get;
		}

		void RemoveI3I4one2manies();


		Allors.R1.Extent<global::Domain.C4> I3C4one2manies
		{ 
			get;
			set;
		}

		void AddI3C4one2many (global::Domain.C4 value);

		void RemoveI3C4one2many (global::Domain.C4 value);

		bool ExistI3C4one2manies
		{
			get;
		}

		void RemoveI3C4one2manies();


		Allors.R1.Extent<global::Domain.I4> I3I4many2manies
		{ 
			get;
			set;
		}

		void AddI3I4many2many (global::Domain.I4 value);

		void RemoveI3I4many2many (global::Domain.I4 value);

		bool ExistI3I4many2manies
		{
			get;
		}

		void RemoveI3I4many2manies();


		global::Domain.I4 I3I4many2one
		{ 
			get;
			set;
		}

		bool ExistI3I4many2one
		{
			get;
		}

		void RemoveI3I4many2one();


		global::Domain.C4 I3C4one2one
		{ 
			get;
			set;
		}

		bool ExistI3C4one2one
		{
			get;
		}

		void RemoveI3C4one2one();


		global::Domain.I4 I3I4one2one
		{ 
			get;
			set;
		}

		bool ExistI3I4one2one
		{
			get;
		}

		void RemoveI3I4one2one();


		global::Domain.C4 I3C4many2one
		{ 
			get;
			set;
		}

		bool ExistI3C4many2one
		{
			get;
		}

		void RemoveI3C4many2one();


		global::System.String I3StringEquals 
		{
			get;
			set;
		}

		bool ExistI3StringEquals{get;}

		void RemoveI3StringEquals();


		global::Domain.C1 C1one2one
		{ 
			get;
			set;
		}

		bool ExistC1one2one
		{
			get;
		}

		void RemoveC1one2one();

	}

}