// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public abstract partial class A34 : A34Allors 
	{
		public A34(Allors.R1.IStrategy allors) : base(allors) {}

		public static A34 Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (A34) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class A34Allors :  Allors.R1.ObjectBase 
	{
		protected A34Allors(Allors.R1.IStrategy allors) : base(allors){}



		virtual public global::System.String A34AllorsString 
		{
			get
			{
				return (global::System.String) Strategy.GetUnitRole(A34Meta.A34AllorsString);
			}
			set
			{
				Strategy.SetUnitRole(A34Meta.A34AllorsString, value);
			}
		}

		virtual public bool ExistA34AllorsString{
			get
			{
				return Strategy.ExistUnitRole(A34Meta.A34AllorsString);
			}
		}

		virtual public void RemoveA34AllorsString()
		{
			Strategy.RemoveUnitRole(A34Meta.A34AllorsString);
		}

	}
}