// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface AI1 :  global::Domain.AS1, Allors.R1.IObject
	{


		global::System.Double? AI1AllorsDouble 
		{
			get;
			set;
		}

		bool ExistAI1AllorsDouble{get;}

		void RemoveAI1AllorsDouble();


		global::System.String AI1AllorsString 
		{
			get;
			set;
		}

		bool ExistAI1AllorsString{get;}

		void RemoveAI1AllorsString();


		global::System.Boolean? AI1AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistAI1AllorsBoolean{get;}

		void RemoveAI1AllorsBoolean();


		global::System.DateTime? AI1AllorsDateTime 
		{
			get;
			set;
		}

		bool ExistAI1AllorsDateTime{get;}

		void RemoveAI1AllorsDateTime();


		global::System.Int32? AI1AllorsInteger 
		{
			get;
			set;
		}

		bool ExistAI1AllorsInteger{get;}

		void RemoveAI1AllorsInteger();


		global::System.Decimal? AI1AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistAI1AllorsDecimal{get;}

		void RemoveAI1AllorsDecimal();

	}

}