// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface AS1 : Allors.IObject
	{


		global::System.Double? AS1AllorsDouble 
		{
			get;
			set;
		}

		bool ExistAS1AllorsDouble{get;}

		void RemoveAS1AllorsDouble();


		global::System.Boolean? AS1AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistAS1AllorsBoolean{get;}

		void RemoveAS1AllorsBoolean();


		global::System.Decimal? AS1AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistAS1AllorsDecimal{get;}

		void RemoveAS1AllorsDecimal();


		global::System.DateTime? AS1AllorsDateTime 
		{
			get;
			set;
		}

		bool ExistAS1AllorsDateTime{get;}

		void RemoveAS1AllorsDateTime();


		global::System.Int32? AS1AllorsInteger 
		{
			get;
			set;
		}

		bool ExistAS1AllorsInteger{get;}

		void RemoveAS1AllorsInteger();


		global::System.String AS1AllorsString 
		{
			get;
			set;
		}

		bool ExistAS1AllorsString{get;}

		void RemoveAS1AllorsString();

	}

}