// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public  partial class ClassWithoutRoles : ClassWithoutRolesAllors 
	{
		public ClassWithoutRoles(Allors.R1.IStrategy allors) : base(allors) {}

		public static ClassWithoutRoles Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (ClassWithoutRoles) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class ClassWithoutRolesAllors :  Allors.R1.ObjectBase 
	{
		protected ClassWithoutRolesAllors(Allors.R1.IStrategy allors) : base(allors){}
	}
}