// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface I12 :  global::Domain.S12, Allors.R1.IObject
	{


		global::System.Boolean? I12AllorsBoolean 
		{
			get;
			set;
		}

		bool ExistI12AllorsBoolean{get;}

		void RemoveI12AllorsBoolean();


		global::System.Int32? I12AllorsInteger 
		{
			get;
			set;
		}

		bool ExistI12AllorsInteger{get;}

		void RemoveI12AllorsInteger();


		Allors.R1.Extent<global::Domain.I34> I12I34one2manies
		{ 
			get;
			set;
		}

		void AddI12I34one2many (global::Domain.I34 value);

		void RemoveI12I34one2many (global::Domain.I34 value);

		bool ExistI12I34one2manies
		{
			get;
		}

		void RemoveI12I34one2manies();


		global::Domain.C3 C3many2one
		{ 
			get;
			set;
		}

		bool ExistC3many2one
		{
			get;
		}

		void RemoveC3many2one();


		global::Domain.C2 I12C2many2one
		{ 
			get;
			set;
		}

		bool ExistI12C2many2one
		{
			get;
		}

		void RemoveI12C2many2one();


		global::System.Double? I12AllorsDouble 
		{
			get;
			set;
		}

		bool ExistI12AllorsDouble{get;}

		void RemoveI12AllorsDouble();


		global::Domain.I34 I12I34many2one
		{ 
			get;
			set;
		}

		bool ExistI12I34many2one
		{
			get;
		}

		void RemoveI12I34many2one();


		Allors.R1.Extent<global::Domain.I34> I12I34many2manies
		{ 
			get;
			set;
		}

		void AddI12I34many2many (global::Domain.I34 value);

		void RemoveI12I34many2many (global::Domain.I34 value);

		bool ExistI12I34many2manies
		{
			get;
		}

		void RemoveI12I34many2manies();


		global::Domain.C3 I12C3one2one
		{ 
			get;
			set;
		}

		bool ExistI12C3one2one
		{
			get;
		}

		void RemoveI12C3one2one();


		Allors.R1.Extent<global::Domain.C2> I12C2many2manies
		{ 
			get;
			set;
		}

		void AddI12C2many2many (global::Domain.C2 value);

		void RemoveI12C2many2many (global::Domain.C2 value);

		bool ExistI12C2many2manies
		{
			get;
		}

		void RemoveI12C2many2manies();


		global::System.Int64? I12AllorsLong 
		{
			get;
			set;
		}

		bool ExistI12AllorsLong{get;}

		void RemoveI12AllorsLong();


		global::System.Decimal? I12AllorsDecimal 
		{
			get;
			set;
		}

		bool ExistI12AllorsDecimal{get;}

		void RemoveI12AllorsDecimal();


		global::Domain.C2 I12C2one2one
		{ 
			get;
			set;
		}

		bool ExistI12C2one2one
		{
			get;
		}

		void RemoveI12C2one2one();


		Allors.R1.Extent<global::Domain.C3> I12C3one2manies
		{ 
			get;
			set;
		}

		void AddI12C3one2many (global::Domain.C3 value);

		void RemoveI12C3one2many (global::Domain.C3 value);

		bool ExistI12C3one2manies
		{
			get;
		}

		void RemoveI12C3one2manies();


		Allors.R1.Extent<global::Domain.C3> I12C3many2manies
		{ 
			get;
			set;
		}

		void AddI12C3many2many (global::Domain.C3 value);

		void RemoveI12C3many2many (global::Domain.C3 value);

		bool ExistI12C3many2manies
		{
			get;
		}

		void RemoveI12C3many2manies();


		global::System.String PrefetchTest 
		{
			get;
			set;
		}

		bool ExistPrefetchTest{get;}

		void RemovePrefetchTest();


		global::System.DateTime? I12AllorsDateTime 
		{
			get;
			set;
		}

		bool ExistI12AllorsDateTime{get;}

		void RemoveI12AllorsDateTime();


		global::System.String I12AllorsString 
		{
			get;
			set;
		}

		bool ExistI12AllorsString{get;}

		void RemoveI12AllorsString();


		global::Domain.I34 I12I34one2one
		{ 
			get;
			set;
		}

		bool ExistI12I34one2one
		{
			get;
		}

		void RemoveI12I34one2one();


		Allors.R1.Extent<global::Domain.C2> I12C2one2manies
		{ 
			get;
			set;
		}

		void AddI12C2one2many (global::Domain.C2 value);

		void RemoveI12C2one2many (global::Domain.C2 value);

		bool ExistI12C2one2manies
		{
			get;
		}

		void RemoveI12C2one2manies();



		global::Domain.C1 C1WhereI12one2one
		{
			get;
		}

		bool ExistC1WhereI12one2one
		{
			get;
		}


		Allors.R1.Extent<global::Domain.I1> I1sWhereI12many2one
		{ 
			get;
		}

		bool ExistI1sWhereI12many2one
		{
			get;
		}


		global::Domain.I1 I1WhereI12one2one
		{
			get;
		}

		bool ExistI1WhereI12one2one
		{
			get;
		}


		Allors.R1.Extent<global::Domain.C1> C1sWhereI12many2one
		{ 
			get;
		}

		bool ExistC1sWhereI12many2one
		{
			get;
		}


		Allors.R1.Extent<global::Domain.I1> I1sWhereI12many2many
		{ 
			get;
		}

		bool ExistI1sWhereI12many2many
		{
			get;
		}


		global::Domain.I1 I1WhereI12one2many
		{
			get;
		}

		bool ExistI1WhereI12one2many
		{
			get;
		}


		global::Domain.C1 C1WhereI12one2many
		{
			get;
		}

		bool ExistC1WhereI12one2many
		{
			get;
		}


		Allors.R1.Extent<global::Domain.C1> C1sWhereI12many2many
		{ 
			get;
		}

		bool ExistC1sWhereI12many2many
		{
			get;
		}

	}

}