// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface IGT32Unit : Allors.R1.IObject
	{


		global::System.String AllorsString2 
		{
			get;
			set;
		}

		bool ExistAllorsString2{get;}

		void RemoveAllorsString2();


		global::System.String AllorsString5 
		{
			get;
			set;
		}

		bool ExistAllorsString5{get;}

		void RemoveAllorsString5();


		global::System.String AllorsString19 
		{
			get;
			set;
		}

		bool ExistAllorsString19{get;}

		void RemoveAllorsString19();


		global::System.String AllorsString18 
		{
			get;
			set;
		}

		bool ExistAllorsString18{get;}

		void RemoveAllorsString18();


		global::System.String AllorsString21 
		{
			get;
			set;
		}

		bool ExistAllorsString21{get;}

		void RemoveAllorsString21();


		global::System.String AllorsString31 
		{
			get;
			set;
		}

		bool ExistAllorsString31{get;}

		void RemoveAllorsString31();


		global::System.String AllorsString15 
		{
			get;
			set;
		}

		bool ExistAllorsString15{get;}

		void RemoveAllorsString15();


		global::System.String AllorsString6 
		{
			get;
			set;
		}

		bool ExistAllorsString6{get;}

		void RemoveAllorsString6();


		global::System.String AllorsString27 
		{
			get;
			set;
		}

		bool ExistAllorsString27{get;}

		void RemoveAllorsString27();


		global::System.String AllorsString11 
		{
			get;
			set;
		}

		bool ExistAllorsString11{get;}

		void RemoveAllorsString11();


		global::System.String AllorsString33 
		{
			get;
			set;
		}

		bool ExistAllorsString33{get;}

		void RemoveAllorsString33();


		global::System.String AllorsString32 
		{
			get;
			set;
		}

		bool ExistAllorsString32{get;}

		void RemoveAllorsString32();


		global::System.String AllorsString25 
		{
			get;
			set;
		}

		bool ExistAllorsString25{get;}

		void RemoveAllorsString25();


		global::System.String AllorsString8 
		{
			get;
			set;
		}

		bool ExistAllorsString8{get;}

		void RemoveAllorsString8();


		global::System.String AllorsString28 
		{
			get;
			set;
		}

		bool ExistAllorsString28{get;}

		void RemoveAllorsString28();


		global::System.String AllorsString29 
		{
			get;
			set;
		}

		bool ExistAllorsString29{get;}

		void RemoveAllorsString29();


		global::System.String AllorsString20 
		{
			get;
			set;
		}

		bool ExistAllorsString20{get;}

		void RemoveAllorsString20();


		global::System.String AllorsString16 
		{
			get;
			set;
		}

		bool ExistAllorsString16{get;}

		void RemoveAllorsString16();


		global::System.String AllorsString30 
		{
			get;
			set;
		}

		bool ExistAllorsString30{get;}

		void RemoveAllorsString30();


		global::System.String AllorsString12 
		{
			get;
			set;
		}

		bool ExistAllorsString12{get;}

		void RemoveAllorsString12();


		global::System.String AllorsString26 
		{
			get;
			set;
		}

		bool ExistAllorsString26{get;}

		void RemoveAllorsString26();


		global::System.String AllorsString17 
		{
			get;
			set;
		}

		bool ExistAllorsString17{get;}

		void RemoveAllorsString17();


		global::System.String AllorsString4 
		{
			get;
			set;
		}

		bool ExistAllorsString4{get;}

		void RemoveAllorsString4();


		global::System.String AllorsString10 
		{
			get;
			set;
		}

		bool ExistAllorsString10{get;}

		void RemoveAllorsString10();


		global::System.String AllorsString23 
		{
			get;
			set;
		}

		bool ExistAllorsString23{get;}

		void RemoveAllorsString23();


		global::System.String AllorsString24 
		{
			get;
			set;
		}

		bool ExistAllorsString24{get;}

		void RemoveAllorsString24();


		global::System.String AllorsString1 
		{
			get;
			set;
		}

		bool ExistAllorsString1{get;}

		void RemoveAllorsString1();


		global::System.String AllorsString14 
		{
			get;
			set;
		}

		bool ExistAllorsString14{get;}

		void RemoveAllorsString14();


		global::System.String AllorsString13 
		{
			get;
			set;
		}

		bool ExistAllorsString13{get;}

		void RemoveAllorsString13();


		global::System.String AllorsString22 
		{
			get;
			set;
		}

		bool ExistAllorsString22{get;}

		void RemoveAllorsString22();


		global::System.String AllorsString3 
		{
			get;
			set;
		}

		bool ExistAllorsString3{get;}

		void RemoveAllorsString3();


		global::System.String AllorsString7 
		{
			get;
			set;
		}

		bool ExistAllorsString7{get;}

		void RemoveAllorsString7();


		global::System.String AllorsString9 
		{
			get;
			set;
		}

		bool ExistAllorsString9{get;}

		void RemoveAllorsString9();

	}

}