// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface ILT32Composite : Allors.R1.IObject
	{


		global::Domain.ILT32Composite Self3
		{ 
			get;
			set;
		}

		bool ExistSelf3
		{
			get;
		}

		void RemoveSelf3();


		global::Domain.ILT32Composite Self2
		{ 
			get;
			set;
		}

		bool ExistSelf2
		{
			get;
		}

		void RemoveSelf2();


		global::Domain.ILT32Composite Self1
		{ 
			get;
			set;
		}

		bool ExistSelf1
		{
			get;
		}

		void RemoveSelf1();



		Allors.R1.Extent<global::Domain.ILT32Composite> ILT32CompositesWhereSelf3
		{ 
			get;
		}

		bool ExistILT32CompositesWhereSelf3
		{
			get;
		}


		Allors.R1.Extent<global::Domain.ILT32Composite> ILT32CompositesWhereSelf2
		{ 
			get;
		}

		bool ExistILT32CompositesWhereSelf2
		{
			get;
		}


		Allors.R1.Extent<global::Domain.ILT32Composite> ILT32CompositesWhereSelf1
		{ 
			get;
		}

		bool ExistILT32CompositesWhereSelf1
		{
			get;
		}

	}

}