// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface ILT32Unit : Allors.IObject
	{


		global::System.String AllorsString1 
		{
			get;
			set;
		}

		bool ExistAllorsString1{get;}

		void RemoveAllorsString1();


		global::System.String AllorsString3 
		{
			get;
			set;
		}

		bool ExistAllorsString3{get;}

		void RemoveAllorsString3();


		global::System.String AllorsString2 
		{
			get;
			set;
		}

		bool ExistAllorsString2{get;}

		void RemoveAllorsString2();

	}

}