// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public partial interface ISandbox : Allors.R1.IObject
	{


		global::System.String InvisibleValue 
		{
			get;
			set;
		}

		bool ExistInvisibleValue{get;}

		void RemoveInvisibleValue();


		Allors.R1.Extent<global::Domain.ISandbox> InvisibleManies
		{ 
			get;
			set;
		}

		void AddInvisibleMany (global::Domain.ISandbox value);

		void RemoveInvisibleMany (global::Domain.ISandbox value);

		bool ExistInvisibleManies
		{
			get;
		}

		void RemoveInvisibleManies();


		global::Domain.ISandbox InvisibleOne
		{ 
			get;
			set;
		}

		bool ExistInvisibleOne
		{
			get;
		}

		void RemoveInvisibleOne();



		Allors.R1.Extent<global::Domain.ISandbox> ISandboxesWhereInvisibleMany
		{ 
			get;
		}

		bool ExistISandboxesWhereInvisibleMany
		{
			get;
		}


		global::Domain.ISandbox ISandboxWhereInvisibleOne
		{
			get;
		}

		bool ExistISandboxWhereInvisibleOne
		{
			get;
		}

	}

}