// Allors generated file. 
// Do not edit this file, changes will be overwritten.
namespace Domain
{
	public  partial class SingleUnit : SingleUnitAllors 
	{
		public SingleUnit(Allors.R1.IStrategy allors) : base(allors) {}

		public static SingleUnit Instantiate (Allors.R1.ISession allorsSession, string allorsObjectId)
		{
			return (SingleUnit) allorsSession.Instantiate(allorsObjectId);		
		}
	}

	[System.Diagnostics.DebuggerNonUserCode]
	public abstract class SingleUnitAllors :  Allors.R1.ObjectBase 
	{
		protected SingleUnitAllors(Allors.R1.IStrategy allors) : base(allors){}



		virtual public global::System.Int32? AllorsInteger 
		{
			get
			{
				return (global::System.Int32?) Strategy.GetUnitRole(SingleUnitMeta.AllorsInteger);
			}
			set
			{
				Strategy.SetUnitRole(SingleUnitMeta.AllorsInteger, value);
			}
		}

		virtual public bool ExistAllorsInteger{
			get
			{
				return Strategy.ExistUnitRole(SingleUnitMeta.AllorsInteger);
			}
		}

		virtual public void RemoveAllorsInteger()
		{
			Strategy.RemoveUnitRole(SingleUnitMeta.AllorsInteger);
		}

	}
}